version: '3'

services:
  postgres:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_DB: onlinetutordb
    env_file:
       - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
  web:
    build: .
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - project:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    restart: always

  # Сервис для Celery
  celery:
    build: .
    command: celery -A online_tutor worker -l info
    volumes:
      - project:/usr/src/app
    depends_on:
      - postgres
      - redis
    restart: always

  # Сервис для Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
  project: