# Generated by Django 4.2 on 2023-07-20 05:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Фамилия"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона только в формате: +996 xxx xxx xxx",
                                regex="^\\+996 \\d{3} \\d{3} \\d{3}$",
                            )
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
                "ordering": ["first_name"],
            },
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Фамилия"),
                ),
                ("age", models.PositiveIntegerField(verbose_name="Возраст")),
                (
                    "phone",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона только в формате: +996 xxx xxx xxx",
                                regex="^\\+996 \\d{3} \\d{3} \\d{3}$",
                            )
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                ("services", models.TextField(verbose_name="Услуги")),
                (
                    "rating",
                    models.FloatField(default=0, verbose_name="Рейтинг"),
                ),
                ("education", models.TextField(verbose_name="Образование")),
                (
                    "consultation_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Стоимость почасовой консультации",
                    ),
                ),
                ("instagram", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Репетитор",
                "verbose_name_plural": "Репетиторы",
                "ordering": ["first_name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCardIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="service_card", verbose_name="Картинка"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Завершен"),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_card_individual",
                        to="core.specialist",
                        verbose_name="Завершено репетитором",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.specialist",
                        verbose_name="Репетитор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Индивидуальное занятие",
                "verbose_name_plural": "Индивидуальные занятия",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCardGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="service_card", verbose_name="Картинка"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Завершен"),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_card_group",
                        to="core.specialist",
                        verbose_name="Завершено репетитором",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.specialist",
                        verbose_name="Репетитор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Групповое занятие",
                "verbose_name_plural": "Групповые занятия",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReviewIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField()),
                (
                    "compledet_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                        verbose_name="Прошедший курс",
                    ),
                ),
                (
                    "service_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.servicecardindividual",
                        verbose_name="Карточка товара",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField()),
                (
                    "compledet_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                        verbose_name="Прошедший курс",
                    ),
                ),
                (
                    "service_card_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.servicecardgroup",
                        verbose_name="Карточка товара",
                    ),
                ),
            ],
        ),
    ]
